### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sisso** [jaredmessenger/unity3d-in-app-purchase-ios#1]
Hi. 

First I like to say thanks for share this code. It was very instructive.

I would like to know if you have any license restriction?

My intention is to create a IOS/Android IAP library as open source, and I would like to use your code as base.

It is stupid to many unity3d developers loosing time and money to do the same thing :P

**Comment by jaredmessenger** [comment]
I'm not really familiar with licensing types, but since I made this code free to everyone I ask that your code is free too. (I know you said open source, but I want it to be clear to anyone else that reads this thread).  I really hate when I see my free code (sometimes slightly modified, most of the time just copied and pasted) on the Unity Asset Store for $50.
